
execute @s ~2 ~ ~1 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~2 ~ ~2 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~1 ~ ~2 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~ ~ ~2 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-1 ~ ~2 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-2 ~ ~1 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-2 ~ ~2 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~2 ~ ~-1 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~2 ~ ~-2 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~1 ~ ~-2 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~ ~ ~-2 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-1 ~ ~-2 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-2 ~ ~-1 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-2 ~ ~-2 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~2 ~ ~ detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-2 ~ ~ detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy

execute @s ~2 ~ ~1 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~2 ~ ~2 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~1 ~ ~2 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~ ~ ~2 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-1 ~ ~2 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-2 ~ ~1 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-2 ~ ~2 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~2 ~ ~-1 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~2 ~ ~-2 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~1 ~ ~-2 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~ ~ ~-2 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-1 ~ ~-2 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-2 ~ ~-1 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-2 ~ ~-2 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~2 ~ ~ detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-2 ~ ~ detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy

execute @s ~2 ~ ~1 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~2 ~ ~2 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~1 ~ ~2 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~ ~ ~2 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-1 ~ ~2 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-2 ~ ~1 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-2 ~ ~2 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~2 ~ ~-1 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~2 ~ ~-2 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~1 ~ ~-2 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~ ~ ~-2 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-1 ~ ~-2 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-2 ~ ~-1 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-2 ~ ~-2 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~2 ~ ~ detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-2 ~ ~ detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy

execute @s ~2 ~ ~1 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~2 ~ ~2 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~1 ~ ~2 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~ ~ ~2 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-1 ~ ~2 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-2 ~ ~1 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-2 ~ ~2 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~2 ~ ~-1 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~2 ~ ~-2 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~1 ~ ~-2 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~ ~ ~-2 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-1 ~ ~-2 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-2 ~ ~-1 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-2 ~ ~-2 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~2 ~ ~ detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-2 ~ ~ detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy

execute @s ~2 ~ ~1 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~2 ~ ~2 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~1 ~ ~2 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~ ~ ~2 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-1 ~ ~2 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-2 ~ ~1 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-2 ~ ~2 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~2 ~ ~-1 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~2 ~ ~-2 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~1 ~ ~-2 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~ ~ ~-2 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-1 ~ ~-2 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-2 ~ ~-1 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-2 ~ ~-2 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~2 ~ ~ detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-2 ~ ~ detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy

execute @s ~2 ~1 ~1 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~2 ~1 ~2 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~1 ~1 ~2 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~ ~1 ~2 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-1 ~1 ~2 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-2 ~1 ~1 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-2 ~1 ~2 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~2 ~1 ~-1 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~2 ~1 ~-2 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~1 ~1 ~-2 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~ ~1 ~-2 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-1 ~1 ~-2 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-2 ~1 ~-1 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-2 ~1 ~-2 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~2 ~1 ~ detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-2 ~1 ~ detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy