execute @s ~4 ~ ~1 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~4 ~ ~2 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~4 ~ ~3 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~4 ~ ~4 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~3 ~ ~4 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~2 ~ ~4 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~1 ~ ~4 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~ ~ ~4 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-1 ~ ~4 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-2 ~ ~4 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-3 ~ ~4 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-4 ~ ~1 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-4 ~ ~2 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-4 ~ ~3 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-4 ~ ~4 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~4 ~ ~-1 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~4 ~ ~-2 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~4 ~ ~-3 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~4 ~ ~-4 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~3 ~ ~-4 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~2 ~ ~-4 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~1 ~ ~-4 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~ ~ ~-4 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-1 ~ ~-4 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-2 ~ ~-4 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-3 ~ ~-4 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-4 ~ ~-1 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-4 ~ ~-2 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-4 ~ ~-3 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-4 ~ ~-4 detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~4 ~ ~ detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy
execute @s ~-4 ~ ~ detect ~ ~ ~ wheat 7 fill ~ ~ ~ ~ ~ ~ wheat 0 destroy

execute @s ~4 ~ ~1 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~4 ~ ~2 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~4 ~ ~3 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~4 ~ ~4 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~3 ~ ~4 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~2 ~ ~4 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~1 ~ ~4 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~ ~ ~4 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-1 ~ ~4 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-2 ~ ~4 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-3 ~ ~4 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-4 ~ ~1 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-4 ~ ~2 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-4 ~ ~3 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-4 ~ ~4 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~4 ~ ~-1 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~4 ~ ~-2 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~4 ~ ~-3 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~4 ~ ~-4 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~3 ~ ~-4 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~2 ~ ~-4 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~1 ~ ~-4 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~ ~ ~-4 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-1 ~ ~-4 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-2 ~ ~-4 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-3 ~ ~-4 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-4 ~ ~-1 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-4 ~ ~-2 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-4 ~ ~-3 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-4 ~ ~-4 detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~4 ~ ~ detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy
execute @s ~-4 ~ ~ detect ~ ~ ~ carrots 7 fill ~ ~ ~ ~ ~ ~ carrots 0 destroy

execute @s ~4 ~ ~1 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~4 ~ ~2 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~4 ~ ~3 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~4 ~ ~4 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~3 ~ ~4 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~2 ~ ~4 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~1 ~ ~4 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~ ~ ~4 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-1 ~ ~4 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-2 ~ ~4 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-3 ~ ~4 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-4 ~ ~1 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-4 ~ ~2 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-4 ~ ~3 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-4 ~ ~4 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~4 ~ ~-1 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~4 ~ ~-2 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~4 ~ ~-3 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~4 ~ ~-4 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~3 ~ ~-4 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~2 ~ ~-4 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~1 ~ ~-4 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~ ~ ~-4 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-1 ~ ~-4 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-2 ~ ~-4 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-3 ~ ~-4 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-4 ~ ~-1 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-4 ~ ~-2 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-4 ~ ~-3 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-4 ~ ~-4 detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~4 ~ ~ detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy
execute @s ~-4 ~ ~ detect ~ ~ ~ potatoes 7 fill ~ ~ ~ ~ ~ ~ potatoes 0 destroy

execute @s ~4 ~ ~1 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~4 ~ ~2 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~4 ~ ~3 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~4 ~ ~4 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~3 ~ ~4 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~2 ~ ~4 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~1 ~ ~4 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~ ~ ~4 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-1 ~ ~4 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-2 ~ ~4 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-3 ~ ~4 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-4 ~ ~1 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-4 ~ ~2 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-4 ~ ~3 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-4 ~ ~4 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~4 ~ ~-1 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~4 ~ ~-2 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~4 ~ ~-3 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~4 ~ ~-4 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~3 ~ ~-4 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~2 ~ ~-4 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~1 ~ ~-4 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~ ~ ~-4 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-1 ~ ~-4 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-2 ~ ~-4 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-3 ~ ~-4 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-4 ~ ~-1 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-4 ~ ~-2 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-4 ~ ~-3 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-4 ~ ~-4 detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~4 ~ ~ detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy
execute @s ~-4 ~ ~ detect ~ ~ ~ beetroot 7 fill ~ ~ ~ ~ ~ ~ beetroot 0 destroy

execute @s ~4 ~ ~1 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~4 ~ ~2 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~4 ~ ~3 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~4 ~ ~4 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~3 ~ ~4 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~2 ~ ~4 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~1 ~ ~4 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~ ~ ~4 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-1 ~ ~4 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-2 ~ ~4 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-3 ~ ~4 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-4 ~ ~1 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-4 ~ ~2 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-4 ~ ~3 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-4 ~ ~4 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~4 ~ ~-1 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~4 ~ ~-2 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~4 ~ ~-3 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~4 ~ ~-4 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~3 ~ ~-4 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~2 ~ ~-4 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~1 ~ ~-4 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~ ~ ~-4 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-1 ~ ~-4 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-2 ~ ~-4 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-3 ~ ~-4 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-4 ~ ~-1 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-4 ~ ~-2 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-4 ~ ~-3 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-4 ~ ~-4 detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~4 ~ ~ detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy
execute @s ~-4 ~ ~ detect ~ ~ ~ nether_wart 3 fill ~ ~ ~ ~ ~ ~ nether_wart 0 destroy

execute @s ~4 ~1 ~1 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~4 ~1 ~2 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~4 ~1 ~3 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~4 ~1 ~4 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~3 ~1 ~4 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~2 ~1 ~4 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~1 ~1 ~4 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~ ~1 ~4 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-1 ~1 ~4 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-2 ~1 ~4 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-3 ~1 ~4 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-4 ~1 ~1 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-4 ~1 ~2 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-4 ~1 ~3 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-4 ~1 ~4 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~4 ~1 ~-1 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~4 ~1 ~-2 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~4 ~1 ~-3 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~4 ~1 ~-4 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~3 ~1 ~-4 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~2 ~1 ~-4 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~1 ~1 ~-4 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~ ~1 ~-4 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-1 ~1 ~-4 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-2 ~1 ~-4 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-3 ~1 ~-4 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-4 ~1 ~-1 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-4 ~1 ~-2 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-4 ~1 ~-3 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-4 ~1 ~-4 detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~4 ~1 ~ detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy
execute @s ~-4 ~1 ~ detect ~ ~ ~ reeds 0 fill ~ ~ ~ ~ ~ ~ reeds 0 destroy


